spring.application.name=springdocker
# Remplace localhost par le nom du container MySQL
spring.datasource.url=jdbc:mysql://mysql-db:3306/demo_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
server.port=8080
